bin/here-xyz.ts
Do not send an empty body on http GET requests
=> Fix accessing xyz

bin/here-xyz.ts, bin/transformutil.ts
fixing issues of list,token,upload
=> fixing issues of list,token,upload

bin/here-xyz.ts, bin/transformutil.ts, package-lock.json, package.json
parallel upload and streaming improvements
=> Stream geojsonl

bin/here-xyz.ts
=> Fixing miner bugs

.gitignore, package-lock.json
See individual commit messages for details
=> 0.2.0 release fixes

src/here-xyz.ts
Adding clientId parameter in all hub api calls.
=> ClientId in hub api calls

src/transformutil.ts
=> -x switch while xyz upload  was not working for uppercase field names in csv

package-lock.json, src/common.ts, src/here-xyz.ts, src/sso.ts
minor bug fix related to TokenAPI call
=> minor bug fix related to TokenAPI call

package-lock.json, package.json, src/common.ts, src/here-xyz.ts, src/sso.ts
version change in package.json and package-lock.json
=> version change in package.json and package-lock.json

bin/beta-terms.txt, src/common.ts, src/here-configure.ts, src/here.ts, src/sso.ts, test/test.js
- Restricting login via appId and appCode.
- Adding support to account-api.
- Using cid to generate token.
=> GA changes Merged

src/common.ts, src/here-xyz.ts
Readonly token while running show command
=> Readonly token for GA

src/here-configure.ts
Fixing bug related to update of tcAccepted flag in accountAPI
=> Updating tcFlag in account-api

package.json
making changes to run script stages for oss, on behalf of Jaidatt
=> script changes in package.json

docs/transform.md, src/here-transform.ts
Reverts heremaps/here-cli#61
@ToonvanStrijp's suggestions were consolidated and edited under #73
=> Revert "output option to transform commands"

.gitignore, docs/transform.md, docs/xyzspace.md, src/here-transform.ts, src/here-xyz.ts, src/transformutil.ts
added transform options -d and -q for setting the delimiter and quote those are passed down to the csv2json library. This adds flexibility for the user so that he/she can use whatever csv format they want.
=> added csv parsing options

src/here-transform.ts, src/transformutil.ts
Minor issues on the csv transform functionality
=> changed for branch issues

package.json
=> Changing package json for release 0.2.5

src/here-xyz.ts, test/test.js
Handling schema validation errors while uploading data
=> Schema validation errs

package-lock.json, package.json, src/here-xyz.ts, src/here.ts, test/test.js
A few minor improvement around the help content, pro beta terms verification and release related changes
=> Release prep

src/here-xyz.ts
=> better error handling while uploading data

src/here-xyz.ts
=> adding confirmation for critical operations

src/here-xyz.ts
Hexbin bug fixes and fine tuning error handling
=> Hexbin bug fixes and fine tuning error handling

bin/pro-beta-terms.txt, src/common.ts
Changing url of pro beta license
=> Changing url of pro beta license

src/here-xyz.ts
…adding force option for clear and delete opertions
=> creation of space when upload command is executed without space id

package-lock.json, package.json
=> setting version to 1.0.1

package-lock.json, package.json, src/here-transform.ts, src/here-xyz.ts, src/transformutil.ts
Issue #12 detect and convert crs of shapefiles if not wgs84
Github#96 - detect fields in CSV that are numbers, and offer to convert
Github#68 - if standard lat/lon fields are not found, list existing fields in the csv
also fixed high vulnerabilities
=> fixing multiple github issues

src/transformutil.ts
fixing issue of --string-fields
=> fixing issue of --string-fields

src/here-xyz.ts, src/transformutil.ts
Adding rule based tagging feature to CLI.
=> RBT 2407 - Rule based tagging

src/here-configure.ts
Default app Id selection prompt will not be shown to user if there is only one appId
=> Default app id prompt fix

src/here-xyz.ts
=> update option for rule based tags

src/here-xyz.ts, src/transformutil.ts
asking string-fields in -a assign option for csv files
=> asking string-fields in -a assign option for csv files

src/here-transform.ts, src/here-xyz.ts
Copy edits to fix documentation
=> Copy edits

src/here-xyz.ts
Github#98 - write source spaceID and description into hexbin space description
=> Github#98 - write source spaceID and description into hexbin space description

src/transformutil.ts
=> fixing a minor issue of processing user defined point field

src/here-xyz.ts, src/hexbin.ts
Fix issue of hexbin creation while using readToken or writeToken
=> Fix issue of hexbin creation while using readToken or writeToken

src/here-xyz.ts
Fixing styling of Stats table output
=> Fixing styling of Stats table output

package-lock.json, package.json
Changing version of fast-csv to latest
=> Changing version of fast-csv to latest

src/here-xyz.ts, src/hexbin.ts
#106 Sum quantitative values in hexbin
=> #106 Sum quantitative values in hexbin - Hexbin aggregate

src/common.ts, src/here-xyz.ts
#137 if *my* space is shared, don't create a new hexbin space
=> #137 if *my* space is shared, don't create a new hexbin space

src/here-xyz.ts
=> #124 Client object fix

src/here-xyz.ts
#133 here xyz upload shape file won't finish uploading
=> #133 here xyz upload shape file won't finish uploading

src/transformutil.ts, test/data/sample.csv
#121 if points are visiting Null Island, convert the `0,0` to a null geometry
=> #121 if points are visiting Null Island, convert the `0,0` to a null geometry

src/here-xyz.ts
=> Adding facility to read schema

src/here-xyz.ts
Adding searchable, tagrules options under config command
=> Adding searchable, tagrules options under config command

package-lock.json, package.json
Changing package version to 1.1.0
=> Changing package version to 1.1.0

src/common.ts, src/here-xyz.ts
Hexbin capability in read token and Connector/Listener Map changes
=> Hexbin capability in read token and Connector/Listener Map changes

src/here-xyz.ts
=> fixing update of rule tag

src/common.ts, src/here-configure.ts, src/here-geocode.ts
Support for API key in geocode feature.
=> Support for API key in geocode feature.

package-lock.json, package.json, src/here-xyz.ts, test/test.js
=> Release 1.2.0

src/here-xyz.ts
=> showing estimated flag in delete/clear operation warnings

package-lock.json, package.json, src/gisUtil.ts, src/here-xyz.ts
GIS refactoring and using d3-delaunay library for voronoi calculation.
=> GIS refactoring and using d3-delaunay library for voronoi calculation.

package-lock.json, src/gisUtil.ts, src/here-xyz.ts, src/transformutil.ts
=> multiple bug fixes

src/here-xyz.ts, src/transformutil.ts
Join command and adding token options in some command
=> Join command and adding token options in some command

src/gisUtil.ts, src/here-xyz.ts, src/transformutil.ts, test/test.js
Gis improvements and other fixes
=> Gis improvements

package-lock.json, package.json
=> fixing vulnerabilities

package-lock.json, package.json
=> changing version to 1.3.1

src/common.ts, src/here-xyz.ts, src/transformutil.ts
=> Non geojson json

package-lock.json, package.json
=> release 1.4.0

package-lock.json, package.json, src/gisUtil.ts, src/here-xyz.ts
some minor fixes and changing version to 1.5
=> some minor fixes and changing version to 1.5

.ort.yml
See [1] for .ort.yml specification.
[1] https://github.com/oss-review-toolkit/ort/blob/master/docs/config-file-ort-yml.md
Signed-off-by: Thomas Steenbergen <thomas.steenbergen@here.com>
=> Update .ort.yml to mark non released dirs and scopes

LICENSE, src/api-error.ts, src/common.ts, src/gisUtil.ts, src/here-configure.ts, src/here-geocode.ts, src/here-transform.ts, src/here-xyz.ts, src/here.ts, src/hexbin.ts, src/requestAsync.ts, src/sso.ts, src/summary.ts, src/transformutil.ts, test/server.js, test/test.js
Please see individual commit messages for details.
=> Fix license and license headers

.travis.yml, scripts/publish-npm.sh
Fix typo in dry run for publish on merge to master.
=> Fixing publish dry run typo.

package-lock.json, package.json, src/common.ts
=> Modify condition for app status check.

src/here-studio.ts
=> checking for projectId before opening webpage in the list

.travis.yml
=> Removing type condition for publish.

.travis.yml
=> Change tag to Travis env variable.

scripts/publish-npm.sh
=> Add branch check command.

tsconfig.json
=> Fix tsc config json.

scripts/publish-npm.sh
=> Skip npm pack test, add install step.

src/transformutil.ts
=> fixing multiple calls in case of --keys option in join command

package-lock.json, package.json
=> changing version in package.json

package-lock.json, package.json
=> fixing Cannot find module 'xlsx' error and 1.6.1 release

.travis.yml, package.json, src/common.ts, src/here-xyz.ts, src/sso.ts
=> Targeted sharing

src/common.ts, src/here-configure.ts
=> fixing issue with local server authorization

src/here-xyz.ts
=> wording fixes for targeted sharing

src/here-xyz.ts, src/here.ts
Title in sharing and fixing ubuntu issue
=> Title in sharing and fixing ubuntu issue

src/here-xyz.ts
=> only give reject option for space that is deleted

LICENSE, README.md, package-lock.json, package.json, src/api-error.ts, src/common.ts, src/geocodeUtil.ts, src/gisUtil.ts, src/here-configure.ts, src/here-geocode.ts, src/here-studio.ts, src/here-transform.ts, src/here-xyz.ts, src/here.ts, src/hexbin.ts, src/requestAsync.ts, src/sso.ts, src/summary.ts, src/transformutil.ts, src/xyzutil.ts, test/server.js, test/test.js
bug fixes - here transform and show -w for targeted sharing
=> bug fixes - here transform and show -w for targeted sharing

.github/workflows/publish.yml
=> Fix publish workflow check tag step.

.github/workflows/publish.yml
=> Fix github actions publish workflow.

.github/workflows/publish.yml
=> Fix regex for tag match.

package-lock.json, package.json, src/common.ts, src/here-xyz.ts
=> fixing issue of adding file tag multiple times in url

package-lock.json, package.json, src/catalogUtil.ts, src/common.ts, src/gisUtil.ts, src/here-catalog.ts, src/here-configure.ts, src/here-interactivemap.ts, src/here-xyz.ts, src/here.ts, src/summary.ts, src/transformutil.ts, src/xyzutil.ts, test/server.js, test/test.js
Adding IML support to HERE CLI
=> Iml support

src/here-interactivemap.ts
Signed-off-by: Ansari, Mujammil <mujammil.ansari@here.com>
=> Update command docs
